### ISSUE TITLE
what is 'Nuke 9',how can i install it?

### ISSUE THREAD

**Issue by andylizi** [cuthb3rt/physics_sim#1]
it need to implement a python module called 'Nuke 9' , what's that?

**Comment by cuthb3rt** [comment]
Hi zhouhaha.

Nuke is a compositing software used a lot in the VFX industry. It's only used to visualise the data after the simulation. It's quite expensive - it's not designed for this simple use - and while there is a non-commercial version, the python commands you can run from there are quite limited, so it probably wouldn't work.

To be honest, this project was intended as a practice for Python coding, using the software I have at my disposal to visualise.

You can still simulate without Nuke, but to render, you would have to write a new module to link with whichever app you chose. I'll take a look at Natron, which is an open source equivalent to Nuke, which has a similar API, so shouldn't take too much work to support...

**Comment by andylizi** [comment]
thank you.
